"""Initial migration

Revision ID: a10559ae9969
Revises: 
Create Date: 2026-09-11 16:05:26.869601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10559ae9969'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('aois',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('preset_key', sa.String(), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('active_alerts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_monitored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aois_id'), 'aois', ['id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aoi_id', sa.String(), nullable=True),
    sa.Column('aoi_name', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('baseline_date', sa.String(), nullable=False),
    sa.Column('recent_date', sa.String(), nullable=False),
    sa.Column('affected_area_hectares', sa.Float(), nullable=False),
    sa.Column('average_delta_index', sa.Float(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('geojson_geometry', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['aoi_id'], ['aois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_id'), 'change_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_events_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_aois_id'), table_name='aois')
    op.drop_table('aois')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
